[package]
name = "imlet"
version = "0.1.0"
edition = "2021"
authors = ["Joel Hilmersson <d.j.hilmersson@egmail.com>"]
description = "A lightweight engine for implicit modeling"
license = "MIT OR Apache-2.0" # Dual-license under MIT or Apache-2.0, a common practice
repository = "https://github.com/joelhi/imlet-rs"
documentation = "https://docs.rs/imlet"
readme = "README.md"
keywords = ["implicit modeling", "mesh generation", "3d geometry", "marching cubes"]
categories = ["3d-geometry","3d-modeling"]
exclude = ["assets/geometry/*"]
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
num-traits = "0.2.19"
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
smallvec = "1.13.2"

# Define features in the project
[features]
viewer = ["bevy","bevy_panorbit_camera","bevy_normal_material", "bevy_egui"]

# Optional dependencies
[dependencies.bevy]
version = "0.14"
optional = true
default-features = false
features = [
  "bevy_winit",
  "bevy_render",
  "bevy_text",
  "default_font",
  "bevy_asset",
]

[dependencies.bevy_panorbit_camera]
version = "0.19.3"
optional = true
features = ["bevy_egui"]

[dependencies.bevy_egui]
version = "0.29.0"
optional = true

[dependencies.bevy_normal_material]
version = "0.6.0"
optional = true

# Profile settings (default optimization)
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1  # Default optimization level for dependencies in dev mode
